#!/usr/bin/env python3
"""Verify PDFs generated by the real extension background worker."""

from __future__ import annotations

import json
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / ".tmp/extension-pdf-matrix"

sys.path.insert(0, str(ROOT))

from scripts.verify_pdf_matrix import (  # noqa: E402
    MEDIA_CHECKBOX_RECTS,
    NON_PARTY_CHECKBOX_RECTS,
    build_cases,
    count_annots,
    count_x_text_ops,
    field_count,
    missing_expected_x_positions,
    pdf_text,
    rendered_x_positions,
    unexpected_x_positions,
)


def run_node_generator() -> None:
    script = ROOT / "scripts/validate_extension_pdf_generation_runner.js"
    result = subprocess.run(["node", str(script)], cwd=ROOT, text=True, capture_output=True)
    if result.returncode != 0:
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(result.returncode)


def verify_pdf(case) -> dict[str, object]:
    path = OUT_DIR / f"extension_{case.name}.pdf"
    text = pdf_text(path)
    checked = set(case.expected_checked_fields) | set(case.expected_manual_overlays)
    rects = MEDIA_CHECKBOX_RECTS if case.values_kind == "media" else NON_PARTY_CHECKBOX_RECTS
    x_positions = rendered_x_positions(path)
    missing_text = [item for item in case.expected_text if item and item not in text]
    forbidden_text = [item for item in case.forbidden_text if item and item in text]
    missing_x = missing_expected_x_positions(checked, x_positions, rects)
    unexpected_x = unexpected_x_positions(checked, x_positions, rects)
    fields = field_count(path)
    annots = count_annots(path)
    x_ops = count_x_text_ops(path)
    failures = []
    if missing_text:
        failures.append(f"missing text: {', '.join(missing_text)}")
    if forbidden_text:
        failures.append(f"forbidden stale text present: {', '.join(forbidden_text)}")
    if missing_x:
        failures.append(f"missing visual X at expected fields: {', '.join(missing_x)}")
    if unexpected_x:
        failures.append(f"unexpected visual X at unchecked fields: {', '.join(unexpected_x)}")
    if fields != 0:
        failures.append(f"PDF still has {fields} form fields")
    if annots != 0:
        failures.append(f"PDF still has {annots} annotations")
    if x_ops < len(checked):
        failures.append(f"visual X count {x_ops} below expected minimum {len(checked)}")
    return {
        "case": f"extension_{case.name}",
        "output": str(path),
        "fields": fields,
        "annots": annots,
        "x_ops": x_ops,
        "expected_min_x": len(checked),
        "ok": not failures,
        "failures": failures,
    }


def main() -> int:
    run_node_generator()
    results = [verify_pdf(case) for case in build_cases()]
    summary_path = OUT_DIR / "summary.json"
    summary_path.write_text(json.dumps(results, indent=2) + "\n")
    failed = [result for result in results if not result["ok"]]
    if failed or len(results) <= 50:
        for result in results:
            status = "PASS" if result["ok"] else "FAIL"
            print(f"{status} {result['case']} fields={result['fields']} annots={result['annots']} x_ops={result['x_ops']}")
            for failure in result["failures"]:
                print(f"  - {failure}")
    else:
        groups = Counter(result["case"].replace("extension_", "", 1).split("_", 3)[0] for result in results)
        exhaustive_groups = Counter(
            "_".join(result["case"].replace("extension_", "", 1).split("_")[:3])
            for result in results
            if result["case"].startswith("extension_exhaustive_")
        )
        representative_count = sum(count for group, count in groups.items() if group != "exhaustive")
        print(f"PASS {len(results)} extension PDF matrix cases")
        print(f"representative_cases={representative_count}")
        for group, count in sorted(exhaustive_groups.items()):
            print(f"{group}={count}")
    print(f"summary={summary_path}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
