#!/usr/bin/env python3
"""Verify PDFs generated by the real extension background worker."""

from __future__ import annotations

import json
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / ".tmp/extension-pdf-matrix"

sys.path.insert(0, str(ROOT))

from scripts.verify_pdf_matrix import (  # noqa: E402
    MEDIA_CHECKBOX_RECTS,
    NON_PARTY_CHECKBOX_RECTS,
    acroform_field_count,
    build_cases,
    count_annots,
    count_x_text_ops,
    field_count,
    missing_expected_x_positions,
    page_count,
    pdf_text,
    rendered_x_positions,
    unexpected_x_positions,
)


def routed_generate_specs() -> list[dict[str, object]]:
    route_results_path = OUT_DIR / "route-results.json"
    route_results = json.loads(route_results_path.read_text(encoding="utf-8")) if route_results_path.exists() else {}
    specs: list[dict[str, object]] = []

    supreme_outputs = sorted(OUT_DIR.glob("*_2026_400001_R_v_Empty_Requested_Docs_media_access_2026.pdf"))
    if len(supreme_outputs) != 1:
        specs.append(
            {
                "case": "extension_generate_supreme_default_docs",
                "output": str(OUT_DIR / "<missing routed generate output>"),
                "fields": 0,
                "annots": 0,
                "x_ops": 0,
                "expected_min_x": 0,
                "ok": False,
                "failures": [f"expected exactly one routed Supreme generate output, found {len(supreme_outputs)}"],
            }
        )
    else:
        specs.append({
            "case": "extension_generate_supreme_default_docs",
            "path": supreme_outputs[0],
            "text": (
                "Perry Duffin",
                "P.Duffin",
                "The Sydney Morning Herald",
                "0466 208 099",
                "perry.duffin@example.com",
                "2026/400001",
                "R",
                "Empty Requested Docs",
                "1-2 June 2026",
                "Exhibit A and Exhibit B",
            ),
            "checked": {"Check Box50", "Check Box51", "Check Box52", "Check Box63", "Check Box64", "Check Box65"},
            "rects": MEDIA_CHECKBOX_RECTS,
            "expected_pages": page_count(ROOT / "extension/forms/access_application_2026.pdf"),
            "forbidden_checked": {"Check Box39", "Check Box40", "Check Box41", "Check Box53", "Check Box54"},
            "applications_effective": route_results.get("supremeDefaultDocs", {}).get("applications_effective"),
            "expected_applications_effective": {"media_access_2026": True, "non_party_access": False},
            "generated_count": len(route_results.get("supremeDefaultDocs", {}).get("generated_files", [])),
            "expected_generated_count": 1,
        })

    local_outputs = sorted(OUT_DIR.glob("*_2026_400002_R_v_Local_Media_Coerced_non_party_access.pdf"))
    stray_local_media_outputs = sorted(OUT_DIR.glob("*_2026_400002_R_v_Local_Media_Coerced_media_access_2026.pdf"))
    if len(local_outputs) != 1 or stray_local_media_outputs:
        specs.append(
            {
                "case": "extension_generate_local_media_coerced",
                "output": str(OUT_DIR / "<missing routed local output>"),
                "fields": 0,
                "annots": 0,
                "x_ops": 0,
                "expected_min_x": 0,
                "ok": False,
                "failures": [
                    f"expected one routed Local non-party output and zero media outputs, found non_party={len(local_outputs)} media={len(stray_local_media_outputs)}"
                ],
            }
        )
    else:
        specs.append({
            "case": "extension_generate_local_media_coerced",
            "path": local_outputs[0],
            "text": (
                "Perry Duffin",
                "P.Duffin",
                "Journalist",
                "The Sydney Morning Herald",
                "0466 208 099",
                "perry.duffin@example.com",
                "2026/400002",
                "R v Local Media Coerced",
                "Downing Centre Local Ct",
                "Current proceedings, media access requested for reporting.",
            ),
            "checked": {
                "Button1",
                "Button4",
                "Button6",
                "Button13",
                "Button37",
                "Button39",
                "Button40",
                "Button41",
                "Button42",
                "Button43",
                "Button44",
                "Button45",
                "Button46",
                "Button47",
            },
            "rects": NON_PARTY_CHECKBOX_RECTS,
            "expected_pages": page_count(ROOT / "extension/forms/application_non_party_access.pdf"),
            "forbidden_checked": {"Button11", "Button12", "Button14", "Button15", "Button16"},
            "applications_effective": route_results.get("localMediaCoerced", {}).get("applications_effective"),
            "expected_applications_effective": {"media_access_2026": False, "non_party_access": True},
            "generated_count": len(route_results.get("localMediaCoerced", {}).get("generated_files", [])),
            "expected_generated_count": 1,
        })
    return specs


def run_node_generator() -> None:
    script = ROOT / "scripts/validate_extension_pdf_generation_runner.js"
    result = subprocess.run(["node", str(script)], cwd=ROOT, text=True, capture_output=True)
    if result.returncode != 0:
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(result.returncode)


def verify_pdf(case) -> dict[str, object]:
    path = OUT_DIR / f"extension_{case.name}.pdf"
    text = pdf_text(path)
    checked = set(case.expected_checked_fields) | set(case.expected_manual_overlays)
    rects = MEDIA_CHECKBOX_RECTS if case.values_kind == "media" else NON_PARTY_CHECKBOX_RECTS
    x_positions = rendered_x_positions(path)
    missing_text = [item for item in case.expected_text if item and item not in text]
    forbidden_text = [item for item in case.forbidden_text if item and item in text]
    missing_x = missing_expected_x_positions(checked, x_positions, rects)
    unexpected_x = unexpected_x_positions(checked, x_positions, rects)
    fields = field_count(path)
    acroform_fields = acroform_field_count(path)
    annots = count_annots(path)
    pages = page_count(path)
    expected_pages = page_count(case.template)
    x_ops = count_x_text_ops(path)
    failures = []
    if missing_text:
        failures.append(f"missing text: {', '.join(missing_text)}")
    if forbidden_text:
        failures.append(f"forbidden stale text present: {', '.join(forbidden_text)}")
    if missing_x:
        failures.append(f"missing visual X at expected fields: {', '.join(missing_x)}")
    if unexpected_x:
        failures.append(f"unexpected visual X at unchecked fields: {', '.join(unexpected_x)}")
    if fields != 0:
        failures.append(f"PDF still has {fields} form fields")
    if acroform_fields != 0:
        failures.append(f"PDF catalog still has {acroform_fields} AcroForm field references")
    if annots != 0:
        failures.append(f"PDF still has {annots} annotations")
    if pages != expected_pages:
        failures.append(f"PDF page count {pages} does not match template page count {expected_pages}")
    if x_ops < len(checked):
        failures.append(f"visual X count {x_ops} below expected minimum {len(checked)}")
    return {
        "case": f"extension_{case.name}",
        "output": str(path),
        "fields": fields,
        "acroform_fields": acroform_fields,
        "annots": annots,
        "pages": pages,
        "expected_pages": expected_pages,
        "x_ops": x_ops,
        "expected_min_x": len(checked),
        "ok": not failures,
        "failures": failures,
    }


def verify_routed_generate(spec: dict[str, object]) -> dict[str, object]:
    if "failures" in spec:
        return spec
    path = spec["path"]
    text = pdf_text(path)
    checked = set(spec["checked"])
    rects = spec["rects"]
    x_positions = rendered_x_positions(path)
    missing_text = [item for item in spec["text"] if item and item not in text]
    missing_x = missing_expected_x_positions(checked, x_positions, rects)
    unexpected_x = unexpected_x_positions(checked, x_positions, rects)
    forbidden_checked = sorted(set(unexpected_x) & set(spec.get("forbidden_checked", set())))
    fields = field_count(path)
    acroform_fields = acroform_field_count(path)
    annots = count_annots(path)
    pages = page_count(path)
    expected_pages = int(spec["expected_pages"])
    x_ops = count_x_text_ops(path)
    failures = []
    if missing_text:
        failures.append(f"missing text: {', '.join(missing_text)}")
    if missing_x:
        failures.append(f"missing visual X at expected fields: {', '.join(missing_x)}")
    if unexpected_x:
        failures.append(f"unexpected visual X at unchecked fields: {', '.join(unexpected_x)}")
    if forbidden_checked:
        failures.append(f"default route ticked non-default documents: {', '.join(forbidden_checked)}")
    if spec.get("applications_effective") != spec.get("expected_applications_effective"):
        failures.append(
            f"applications_effective mismatch: got {spec.get('applications_effective')} expected {spec.get('expected_applications_effective')}"
        )
    if spec.get("generated_count") != spec.get("expected_generated_count"):
        failures.append(
            f"generated file count mismatch: got {spec.get('generated_count')} expected {spec.get('expected_generated_count')}"
        )
    if fields != 0:
        failures.append(f"PDF still has {fields} form fields")
    if acroform_fields != 0:
        failures.append(f"PDF catalog still has {acroform_fields} AcroForm field references")
    if annots != 0:
        failures.append(f"PDF still has {annots} annotations")
    if pages != expected_pages:
        failures.append(f"PDF page count {pages} does not match expected routed page count {expected_pages}")
    return {
        "case": spec["case"],
        "output": str(path),
        "fields": fields,
        "acroform_fields": acroform_fields,
        "annots": annots,
        "pages": pages,
        "expected_pages": expected_pages,
        "x_ops": x_ops,
        "expected_min_x": len(checked),
        "ok": not failures,
        "failures": failures,
    }


def main() -> int:
    run_node_generator()
    results = [verify_pdf(case) for case in build_cases()]
    results.extend(verify_routed_generate(spec) for spec in routed_generate_specs())
    summary_path = OUT_DIR / "summary.json"
    summary_path.write_text(json.dumps(results, indent=2) + "\n")
    failed = [result for result in results if not result["ok"]]
    if failed or len(results) <= 50:
        for result in results:
            status = "PASS" if result["ok"] else "FAIL"
            print(f"{status} {result['case']} fields={result['fields']} annots={result['annots']} x_ops={result['x_ops']}")
            for failure in result["failures"]:
                print(f"  - {failure}")
    else:
        groups = Counter(result["case"].replace("extension_", "", 1).split("_", 3)[0] for result in results)
        exhaustive_groups = Counter(
            "_".join(result["case"].replace("extension_", "", 1).split("_")[:3])
            for result in results
            if result["case"].startswith("extension_exhaustive_")
        )
        representative_count = sum(count for group, count in groups.items() if group != "exhaustive")
        print(f"PASS {len(results)} extension PDF matrix cases")
        print(f"representative_cases={representative_count}")
        for group, count in sorted(exhaustive_groups.items()):
            print(f"{group}={count}")
    print(f"summary={summary_path}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
